apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: micro-recognizer-waker
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: micro-recognizer-waker
            image: byrnedo/alpine-curl
			env:
            - name: DBSECRET
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: password
            command: ["/bin/sh"]
            args: ["-c", "curl -H \"Authorization: $DBSECRET\" -H \"ReqFromCron: true\" -X POST \"http://recognizer-api-dev.gitlab-managed-apps.svc.cluster.local:8080/recognizer/sendImgs\""]

          restartPolicy: OnFailure

