apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: micro-recognizer-waker
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: micro-recognizer-waker
            image: byrnedo/alpine-curl
            command: ["/bin/sh"]
            args: ["-c", "curl -X POST \"http://recognizer-api.gitlab-managed-apps.svc.cluster.local:8080/recognizer/sendImgs\""]
            
          restartPolicy: OnFailure

