apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: micro-recognizer-waker
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: micro-recognizer-waker
            image: byrnedo/alpine-curl
            envFrom:
            - secretRef:
                name: database-secrets
                key: password
            command: ["/bin/sh"]
            args: ["-c", "curl -H "Authorization: $database-secrets" -H "ReqFromCron: true" -X POST \"http://recognizer-dev-api.gitlab-managed-apps.svc.cluster.local:8080/recognizer/sendImgs\""]

          restartPolicy: OnFailure

