apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: micro-recognizer-waker
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: micro-recognizer-waker
            image: byrnedo/alpine-curl
            args:
            - /bin/sh
            - -c
            - curl -s -X POST "http://recognizer-api-dev.gitlab-managed-apps.svc.cluster.local:8080/recognizer/sendImgs"

          restartPolicy: OnFailure

