apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: micro-recognizer-waker
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: micro-recognizer-waker
            image: byrnedo/alpine-curl
            command: ["/bin/sh"]
            args: ["-ec", "curl -X POST \"http://recognizer-api-dev.gitlab-managed-apps.svc.cluster.local:8080/recognizer/sendImgs\""]
            
          restartPolicy: OnFailure

