apiVersion: v1
kind: Service
metadata:
  name: recognizer-api
  namespace: gitlab-managed-apps
spec:
  selector:
    app: recognizer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: recognizer-api-dev
  namespace: gitlab-managed-apps
spec:
  selector:
    app: recognizer-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
